### ISSUE TITLE
Fedex Tracking number not getting matched

### ISSUE THREAD

**Issue by mfischman** [darkain/php-tracking-urls#4]
Fedex may have tracking numbers from 9-22 digits according to their phone support. This is an example of a Fedex tracking number that is not getting matched ...
00408017007469

**Comment by darkain** [comment]
Google's tracking number search doesn't work with that particular tracking number either.

Additionally, putting it into the FedEx website itself, FedEx drops the first two 0's at the beginning of that number. The resulting number, "408017007469", works with this library, Google's tracking number search, and FedEx's web site.

I'm not sure where these leading 0's came from, but they look like they're not supposed to be apart of the main tracking number.

**Comment by mfischman** [comment]
on my environment, Fedex does not drop the leading zeros. These tracking numbers are generated by fedex with the leading zeros. I called fedex to verify and they told me that the tracking numbers could be any number of digits between 9-22.

**Comment by darkain** [comment]
Fixed in: https://github.com/darkain/php-tracking-urls/commit/9d1a6bc5294b457e735bff6fac9b1551e9eaad9c
