### ISSUE TITLE
USPS 26 digits not found - simple patch

### ISSUE THREAD

**Issue by mgtremaine** [darkain/php-tracking-urls#5]
Example Tracking ID for you tests   
'92748963438592543475924253'            => 'usps.com',

Fix line 5 by adding ",6" to the last optional match  so the range is 2 to 6 on that test. You can do other things but that seemed simple enough and unlikely to throw a false positive.

                        'url'=>'https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=',
                        'reg'=>'/\b((420 ?\d{5} ?)?(91|92|93|94|01|03|04|70|23|13)\d{2} ?\d{4} ?\d{4} ?\d{4} ?\d{4}( ?\d{2,6})?)\b/i'

**Comment by darkain** [comment]
Patch has been applied, thanks for the info! https://github.com/darkain/php-tracking-urls/commit/2c3b1f6d1fba308361f51043a1bd83a428c863b1
