### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by philipnewcomer** [darkain/php-tracking-urls#6]
Hi, can you please add this library to https://packagist.org/, so we can install it using the Composer dependency manager?

I'd be happy to provide a PR with a composer.json file if needed; you'd just need to create an account on packagist and publish it.

**Comment by jesusfbn** [comment]
I second that it would be great if we can get this library on [https://packagist.org/](https://packagist.org/)

**Comment by darkain** [comment]
https://github.com/darkain/php-tracking-urls/commit/1dfdf814d0bb864f954f109fb0b74f3f0fe2f182 I've added the composer.json file. I personally dont use composer/packagist, so I hope what I did will work. If it does, please let me know so I can also add this to other projects I manage.

https://packagist.org/packages/darkain/php-tracking-urls

**Comment by philipnewcomer** [comment]
I tested and it's working, thanks.

**Comment by darkain** [comment]
Cool, thanks. Glad to know! I'll work on integrating this into other projects I manage now too.
